/**
 * Server Side Rendering
 */
import { APIGatewayEvent } from "aws-lambda";
import { StaticRouter } from "react-router-dom/server";
import * as React from "react";
import { renderToString } from "react-dom/server";

import App from "../App";
import ConfigContext from "../components/ConfigContext";
import config from "./config";
import html from "./html";
import { Stats } from "./types";
import Header from "../components/Header";

/**
 * Server-side rendering
 */
export default async function render(event: APIGatewayEvent): Promise<string> {
  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
  const stats = (await import("../../dist/stats.json")) as unknown as Stats;
  let location: string = event.path
  if (event.queryStringParameters) {
    const searchParams = new URLSearchParams()
    Object.entries(event.queryStringParameters).forEach(([key, value]) => searchParams.append(key, value ?? ''))
    location += `?${searchParams.toString()}`
  }
  const content = renderToString(
    <ConfigContext.Provider value={config}>
      <StaticRouter location={location}>
        <App />
      </StaticRouter>
    </ConfigContext.Provider>,
  );
  return html({ stats, content, config });
}
